# Generated by Django 4.1 on 2022-11-23 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0002_cardealer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
